name: /Users/nadupoy/Documents/Programming/Machine Learning/Study/Mathematics of
  Machine Learning/math-of-ml
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - joblib=1.5.3=py314hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.30=hf2bb037_2
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - numpy=2.4.1=py314hde9b8b7_0
  - numpy-base=2.4.1=py314hb4b2851_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyh0d26453_0
  - python=3.14.2=h1858270_101_cp314
  - python_abi=3.14=2_cp314
  - readline=8.3=h0b18652_0
  - scikit-learn=1.8.0=py314hfa3d80f_0
  - scipy=1.16.3=py314h18857b0_0
  - sqlite=3.51.1=hab6afd1_0
  - threadpoolctl=3.5.0=py314h7136c26_1
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /Users/nadupoy/Documents/Programming/Machine Learning/Study/Mathematics 
  of Machine Learning/math-of-ml
